version: '3.4'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - BUILD_CONTEXT=backend
    ports:
      - 3001:3001
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - BUILD_CONTEXT=frontend
        - API_URL=http://localhost:3001
    ports:
      - 3000:3000

