name: Push stack to heroku
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      BACKEND_APP_NAME: klau-package-viewer-backend
      FRONTEND_APP_NAME: klau-package-viewer-frontend
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_SECRET }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Create Heroku app and add remote for backend
        id: create-backend
        run: heroku create ${BACKEND_APP_NAME} --remote ${BACKEND_APP_NAME}
        continue-on-error: true
      - name: Add Heroku buildpacks if app was created on previous step
        if: steps.create-backend.outcome == 'success'
        run: |
          heroku buildpacks:add -a ${BACKEND_APP_NAME} heroku-community/multi-procfile
          heroku buildpacks:add -a ${BACKEND_APP_NAME} heroku/nodejs
      - name: Set procfile
        run: heroku config:set -a ${BACKEND_APP_NAME} PROCFILE=apps/backend/Procfile APP=backend
      - name: Set remote and push to Heroku
        run: |
          heroku git:remote -a ${BACKEND_APP_NAME} -r ${BACKEND_APP_NAME}
          git push ${BACKEND_APP_NAME} HEAD:main -f

      - name: Create Heroku app and add remote for frontend
        id: create-frontend
        run: heroku create ${FRONTEND_APP_NAME} --remote ${FRONTEND_APP_NAME}
        continue-on-error: true
      - name: Add Heroku buildpacks if app was created on previous step
        if: steps.create-frontend.outcome == 'success'
        run: |
          heroku buildpacks:add -a ${FRONTEND_APP_NAME} heroku-community/multi-procfile
          heroku buildpacks:add -a ${FRONTEND_APP_NAME} heroku/nodejs
      - name: Set procfile
        run: heroku config:set -a ${FRONTEND_APP_NAME} PROCFILE=apps/frontend/Procfile APP=frontend NEXT_PUBLIC_API_URL=https://klau-package-viewer-backend.herokuapp.com
      - name: Set remote and push to Heroku
        run: |
          heroku git:remote -a ${FRONTEND_APP_NAME} -r ${FRONTEND_APP_NAME}
          git push ${FRONTEND_APP_NAME} HEAD:main -f


    
    